console.log(process.version, '// 설치된 노드의 버전입니다.');
console.log(process.arch, '// 프로세서 아키텍처 정보입니다. arm, ia32 등의 값일 수도 있습니다.');
console.log(process.platform, '// 운영체제 플랫폼 정보입니다. linux나 darwin, freebsd 등의 값일 수도 있습니다.');
console.log(process.pid, '// 현재 프로세스 아이디입니다. 프로세스를 여러 개 가질 때 구분할 수 있습니다.');
console.log(process.uptime(), '// 프로세스가 시작된 후 흐른 시간입니다. 단위는 초입니다.');
console.log(process.execPath, '// 노드의 경로입니다.');
console.log(process.cwd(), '// 현재 프로세스가 실행되는 위치입니다.');
console.log(process.cpuUsage(), '// 현재 cpu 사용량입니다.');
console.log(process.env);
const secretId = process.env.SECRET_ID;
const secretCode = process.env.SECRET_CODE;
console.log(secretId, secretCode);
console.log(process.env.SECRET_ID);
console.log(process.env.SECRET_CODE);